<?php $ret['data'] = array(
    array(),
    array('id'=>'uk-icon-adjust', 'text'=>'adjust'),
    array('id'=>'uk-icon-anchor', 'text'=>'anchor'),
    array('id'=>'uk-icon-archive', 'text'=>'archive'),
    array('id'=>'uk-icon-area-chart', 'text'=>'area-chart'),
    array('id'=>'uk-icon-arrows', 'text'=>'arrows'),
    array('id'=>'uk-icon-arrows uk-icon-spin', 'text'=>'arrows <span class="uk-text-muted">(spin)</span>'),
    array('id'=>'uk-icon-arrows-h', 'text'=>'arrows-h'),
    array('id'=>'uk-icon-arrows-v', 'text'=>'arrows-v'),
    array('id'=>'uk-icon-asterisk', 'text'=>'asterisk'),
    array('id'=>'uk-icon-asterisk uk-icon-spin', 'text'=>'asterisk <span class="uk-text-muted">(spin)</span>'),
    array('id'=>'uk-icon-at', 'text'=>'at'),
    array('id'=>'uk-icon-automobile', 'text'=>'automobile <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-balance-scale', 'text'=>'balance-scale'),
    array('id'=>'uk-icon-ban', 'text'=>'ban'),
    array('id'=>'uk-icon-ban uk-icon-spin', 'text'=>'ban <span class="uk-text-muted">(spin)</spn>'),
    array('id'=>'uk-icon-bank', 'text'=>'bank <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-bar-chart', 'text'=>'bar-chart'),
    array('id'=>'uk-icon-bar-chart-o', 'text'=>'bar-chart-o <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-barcode', 'text'=>'barcode'),
    array('id'=>'uk-icon-bars', 'text'=>'bars'),
    array('id'=>'uk-icon-battery-empty', 'text'=>'battery-empty <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-battery-0', 'text'=>'battery-0'),
    array('id'=>'uk-icon-battery-quarter', 'text'=>'battery-quarter <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-battery-1', 'text'=>'battery-1'),
    array('id'=>'uk-icon-battery-half', 'text'=>'battery-half <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-battery-2', 'text'=>'battery-2'),
    array('id'=>'uk-text-truncate"><i class="uk-icon-battery-three-quarters', 'text'=>'battery-three-quarters <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-battery-3', 'text'=>'battery-3'),
    array('id'=>'uk-icon-battery-full', 'text'=>'battery-full <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-battery-4', 'text'=>'battery-4'),
    array('id'=>'uk-icon-bed', 'text'=>'bed'),
    array('id'=>'uk-icon-beer', 'text'=>'beer'),
    array('id'=>'uk-icon-bell', 'text'=>'bell'),
    array('id'=>'uk-icon-bell-o', 'text'=>'bell-o'),
    array('id'=>'uk-icon-bell-slash', 'text'=>'bell-slash'),
    array('id'=>'uk-icon-bell-slash-o', 'text'=>'bell-slash-o'),
    array('id'=>'uk-icon-bicycle', 'text'=>'bicycle'),
    array('id'=>'uk-icon-binoculars', 'text'=>'binoculars'),
    array('id'=>'uk-icon-birthday-cake', 'text'=>'birthday-cake'),
    array('id'=>'uk-icon-bluetooth', 'text'=>'bluetooth'),
    array('id'=>'uk-icon-bluetooth-b', 'text'=>'bluetooth-b'),
    array('id'=>'uk-icon-bolt', 'text'=>'bolt'),
    array('id'=>'uk-icon-bomb', 'text'=>'bomb'),
    array('id'=>'uk-icon-book', 'text'=>'book'),
    array('id'=>'uk-icon-bookmark', 'text'=>'bookmark'),
    array('id'=>'uk-icon-bookmark-o', 'text'=>'bookmark-o'),
    array('id'=>'uk-icon-briefcase', 'text'=>'briefcase'),
    array('id'=>'uk-icon-bug', 'text'=>'bug'),
    array('id'=>'uk-icon-bug uk-icon-spin', 'text'=>'bug <span class="uk-text-muted">(spin)</span>'),
    array('id'=>'uk-icon-building', 'text'=>'building'),
    array('id'=>'uk-icon-building-o', 'text'=>'building-o'),
    array('id'=>'uk-icon-bullhorn', 'text'=>'bullhorn'),
    array('id'=>'uk-icon-bullseye', 'text'=>'bullseye'),
    array('id'=>'uk-icon-bus', 'text'=>'bus'),
    array('id'=>'uk-icon-cab', 'text'=>'cab <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-calculator', 'text'=>'calculator'),
    array('id'=>'uk-icon-calendar', 'text'=>'calendar'),
    array('id'=>'uk-icon-calendar-check-o', 'text'=>'calendar-check-o'),
    array('id'=>'uk-icon-calendar-minus-o', 'text'=>'calendar-minus-o'),
    array('id'=>'uk-icon-calendar-o', 'text'=>'calendar-o'),
    array('id'=>'uk-icon-calendar-plus-o', 'text'=>'calendar-plus-o'),
    array('id'=>'uk-icon-calendar-times-o', 'text'=>'calendar-times-o'),
    array('id'=>'uk-icon-camera', 'text'=>'camera'),
    array('id'=>'uk-icon-camera-retro', 'text'=>'camera-retro'),
    array('id'=>'uk-icon-car', 'text'=>'car'),
    array('id'=>'uk-icon-caret-square-o-down', 'text'=>'caret-square-o-down'),
    array('id'=>'uk-icon-caret-square-o-left', 'text'=>'caret-square-o-left'),
    array('id'=>'uk-icon-caret-square-o-right', 'text'=>'caret-square-o-right'),
    array('id'=>'uk-icon-caret-square-o-up', 'text'=>'caret-square-o-up'),
    array('id'=>'uk-icon-cart-arrow-down', 'text'=>'cart-arrow-down'),
    array('id'=>'uk-icon-cart-plus', 'text'=>'cart-plus'),
    array('id'=>'uk-icon-cc', 'text'=>'cc'),
    array('id'=>'uk-icon-certificate', 'text'=>'certificate'),
    array('id'=>'uk-icon-check', 'text'=>'check'),
    array('id'=>'uk-icon-check-circle', 'text'=>'check-circle'),
    array('id'=>'uk-icon-check-circle-o', 'text'=>'check-circle-o'),
    array('id'=>'uk-icon-check-square', 'text'=>'check-square'),
    array('id'=>'uk-icon-check-square-o', 'text'=>'check-square-o'),
    array('id'=>'uk-icon-child', 'text'=>'child'),
    array('id'=>'uk-icon-circle', 'text'=>'circle'),
    array('id'=>'uk-icon-circle-o', 'text'=>'circle-o'),
    array('id'=>'uk-icon-circle-o-notch', 'text'=>'circle-o-notch'),
    array('id'=>'uk-icon-circle-o-notch uk-icon-spin', 'text'=>'circle-o-notch <span class="uk-text-muted">(spin)</span>'),
    array('id'=>'uk-icon-circle-thin', 'text'=>'circle-thin'),
    array('id'=>'uk-icon-clock-o', 'text'=>'clock-o'),
    array('id'=>'uk-icon-clock-o uk-icon-spin', 'text'=>'clock-o <span class="uk-text-muted">(spin)</span>'),
    array('id'=>'uk-icon-clone', 'text'=>'clone'),
    array('id'=>'uk-icon-close', 'text'=>'close <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-cloud', 'text'=>'cloud'),
    array('id'=>'uk-icon-cloud-download', 'text'=>'cloud-download'),
    array('id'=>'uk-icon-cloud-upload', 'text'=>'cloud-upload'),
    array('id'=>'uk-icon-code', 'text'=>'code'),
    array('id'=>'uk-icon-code-fork', 'text'=>'code-fork'),
    array('id'=>'uk-icon-coffee', 'text'=>'coffee'),
    array('id'=>'uk-icon-cog', 'text'=>'cog'),
    array('id'=>'uk-icon-cog uk-icon-spin', 'text'=>'cog <span class="uk-text-muted">(spin)</span>'),
    array('id'=>'uk-icon-cogs', 'text'=>'cogs'),
    array('id'=>'uk-icon-comment', 'text'=>'comment'),
    array('id'=>'uk-icon-comment-o', 'text'=>'comment-o'),
    array('id'=>'uk-icon-commenting', 'text'=>'commenting'),
    array('id'=>'uk-icon-commenting-o', 'text'=>'commenting-o'),
    array('id'=>'uk-icon-comments', 'text'=>'comments'),
    array('id'=>'uk-icon-comments-o', 'text'=>'comments-o'),
    array('id'=>'uk-icon-compass', 'text'=>'compass'),
    array('id'=>'uk-icon-compass uk-icon-spin', 'text'=>'compass <span class="uk-text-muted">(spin)</span>'),
    array('id'=>'uk-icon-copyright', 'text'=>'copyright'),
    array('id'=>'uk-icon-creative-commons', 'text'=>'creative-commons'),
    array('id'=>'uk-icon-credit-card', 'text'=>'credit-card'),
    array('id'=>'uk-icon-credit-card-alt', 'text'=>'credit-card-alt'),
    array('id'=>'uk-icon-crop', 'text'=>'crop'),
    array('id'=>'uk-icon-crosshairs', 'text'=>'crosshairs'),
    array('id'=>'uk-icon-crosshairs uk-icon-spin', 'text'=>'crosshairs <span class="uk-text-muted">(spin)</span>'),
    array('id'=>'uk-icon-cube', 'text'=>'cube'),
    array('id'=>'uk-icon-cubes', 'text'=>'cubes'),
    array('id'=>'uk-icon-cutlery', 'text'=>'cutlery'),
    array('id'=>'uk-icon-dashboard', 'text'=>'dashboard <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-database', 'text'=>'database'),
    array('id'=>'uk-icon-desktop', 'text'=>'desktop'),
    array('id'=>'uk-icon-diamond', 'text'=>'diamond'),
    array('id'=>'uk-icon-dot-circle-o', 'text'=>'dot-circle-o'),
    array('id'=>'uk-icon-download', 'text'=>'download'),
    array('id'=>'uk-icon-edit', 'text'=>'edit <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-ellipsis-h', 'text'=>'ellipsis-h'),
    array('id'=>'uk-icon-ellipsis-h uk-icon-spin', 'text'=>'ellipsis-h <span class="uk-text-muted">(spin)</span>'),
    array('id'=>'uk-icon-ellipsis-v', 'text'=>'ellipsis-v'),
    array('id'=>'uk-icon-envelope', 'text'=>'envelope'),
    array('id'=>'uk-icon-envelope-o', 'text'=>'envelope-o'),
    array('id'=>'uk-icon-envelope-square', 'text'=>'envelope-square'),
    array('id'=>'uk-icon-eraser', 'text'=>'eraser'),
    array('id'=>'uk-icon-exchange', 'text'=>'exchange'),
    array('id'=>'uk-icon-exclamation', 'text'=>'exclamation'),
    array('id'=>'uk-icon-exclamation-circle', 'text'=>'exclamation-circle'),
    array('id'=>'uk-icon-exclamation-triangle', 'text'=>'exclamation-triangle'),
    array('id'=>'uk-icon-external-link', 'text'=>'external-link'),
    array('id'=>'uk-icon-external-link-square', 'text'=>'external-link-square'),
    array('id'=>'uk-icon-eye', 'text'=>'eye'),
    array('id'=>'uk-icon-eye-slash', 'text'=>'eye-slash'),
    array('id'=>'uk-icon-eyedropper', 'text'=>'eyedropper'),
    array('id'=>'uk-icon-fax', 'text'=>'fax'),
    array('id'=>'uk-icon-female', 'text'=>'female'),
    array('id'=>'uk-icon-fighter-jet', 'text'=>'fighter-jet'),
    array('id'=>'uk-icon-file-archive-o', 'text'=>'file-archive-o'),
    array('id'=>'uk-icon-file-audio-o', 'text'=>'file-audio-o'),
    array('id'=>'uk-icon-file-code-o', 'text'=>'file-code-o'),
    array('id'=>'uk-icon-file-excel-o', 'text'=>'file-excel-o'),
    array('id'=>'uk-icon-file-image-o', 'text'=>'file-image-o'),
    array('id'=>'uk-icon-file-movie-o', 'text'=>'file-movie-o <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-file-pdf-o', 'text'=>'file-pdf-o'),
    array('id'=>'uk-icon-file-photo-o', 'text'=>'file-photo-o <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-file-picture-o', 'text'=>'file-picture-o <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-file-powerpoint-o', 'text'=>'file-powerpoint-o'),
    array('id'=>'uk-icon-file-sound-o', 'text'=>'file-sound-o <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-file-video-o', 'text'=>'file-video-o'),
    array('id'=>'uk-icon-file-word-o', 'text'=>'file-word-o'),
    array('id'=>'uk-icon-file-zip-o', 'text'=>'file-zip-o <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-film', 'text'=>'film'),
    array('id'=>'uk-icon-filter', 'text'=>'filter'),
    array('id'=>'uk-icon-fire', 'text'=>'fire'),
    array('id'=>'uk-icon-fire-extinguisher', 'text'=>'fire-extinguisher'),
    array('id'=>'uk-icon-flag', 'text'=>'flag'),
    array('id'=>'uk-icon-flag-checkered', 'text'=>'flag-checkered'),
    array('id'=>'uk-icon-flag-o', 'text'=>'flag-o'),
    array('id'=>'uk-icon-flash', 'text'=>'flash <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-flask', 'text'=>'flask'),
    array('id'=>'uk-icon-folder', 'text'=>'folder'),
    array('id'=>'uk-icon-folder-o', 'text'=>'folder-o'),
    array('id'=>'uk-icon-folder-open', 'text'=>'folder-open'),
    array('id'=>'uk-icon-folder-open-o', 'text'=>'folder-open-o'),
    array('id'=>'uk-icon-frown-o', 'text'=>'frown-o'),
    array('id'=>'uk-icon-futbol-o', 'text'=>'futbol-o'),
    array('id'=>'uk-icon-futbol-o uk-icon-spin', 'text'=>'futbol-o <span class="uk-text-muted">(spin)</span>'),
    array('id'=>'uk-icon-gamepad', 'text'=>'gamepad'),
    array('id'=>'uk-icon-gavel', 'text'=>'gavel'),
    array('id'=>'uk-icon-gear', 'text'=>'gear <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-gears', 'text'=>'gears <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-genderless', 'text'=>'genderless <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-gift', 'text'=>'gift'),
    array('id'=>'uk-icon-glass', 'text'=>'glass'),
    array('id'=>'uk-icon-globe', 'text'=>'globe'),
    array('id'=>'uk-icon-graduation-cap', 'text'=>'graduation-cap'),
    array('id'=>'uk-icon-group', 'text'=>'group <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-hand-lizard-o', 'text'=>'hand-lizard-o'),
    array('id'=>'uk-icon-hand-stop-o', 'text'=>'hand-stop-o <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-hand-paper-o', 'text'=>'hand-paper-o'),
    array('id'=>'uk-icon-hand-peace-o', 'text'=>'hand-peace-o'),
    array('id'=>'uk-icon-hand-pointer-o', 'text'=>'hand-pointer-o'),
    array('id'=>'uk-icon-hand-grab-o', 'text'=>'hand-grab-o <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-hand-rock-o', 'text'=>'hand-rock-o'),
    array('id'=>'uk-icon-hand-scissors-o', 'text'=>'hand-scissors-o'),
    array('id'=>'uk-icon-hand-spock-o', 'text'=>'hand-spock-o'),
    array('id'=>'uk-icon-hdd-o', 'text'=>'hdd-o'),
    array('id'=>'uk-icon-hashtag', 'text'=>'hashtag'),
    array('id'=>'uk-icon-headphones', 'text'=>'headphones'),
    array('id'=>'uk-icon-heart', 'text'=>'heart'),
    array('id'=>'uk-icon-heart-o', 'text'=>'heart-o'),
    array('id'=>'uk-icon-heartbeat', 'text'=>'heartbeat'),
    array('id'=>'uk-icon-history', 'text'=>'history'),
    array('id'=>'uk-icon-home', 'text'=>'home'),
    array('id'=>'uk-icon-hotel', 'text'=>'hotel <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-hourglass', 'text'=>'hourglass'),
    array('id'=>'uk-icon-hourglass uk-icon-spin', 'text'=>'hourglass <span class="uk-text-muted">(spin)</span>'),
    array('id'=>'uk-icon-hourglass-o', 'text'=>'hourglass-o'),
    array('id'=>'uk-icon-hourglass-o uk-icon-spin', 'text'=>'hourglass-o <span class="uk-text-muted">(spin)</span>'),
    array('id'=>'uk-icon-hourglass-1', 'text'=>'hourglass-1 <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-hourglass-start', 'text'=>'hourglass-start'),
    array('id'=>'uk-icon-hourglass-2', 'text'=>'hourglass-2 <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-hourglass-half', 'text'=>'hourglass-half'),
    array('id'=>'uk-icon-hourglass-3', 'text'=>'hourglass-3 <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-hourglass-end', 'text'=>'hourglass-end'),
    array('id'=>'uk-icon-i-cursor', 'text'=>'i-cursor'),
    array('id'=>'uk-icon-image', 'text'=>'image <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-inbox', 'text'=>'inbox'),
    array('id'=>'uk-icon-industry', 'text'=>'industry'),
    array('id'=>'uk-icon-info', 'text'=>'info'),
    array('id'=>'uk-icon-info-circle', 'text'=>'info-circle'),
    array('id'=>'uk-icon-institution', 'text'=>'institution <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-key', 'text'=>'key'),
    array('id'=>'uk-icon-keyboard-o', 'text'=>'keyboard-o'),
    array('id'=>'uk-icon-language', 'text'=>'language'),
    array('id'=>'uk-icon-laptop', 'text'=>'laptop'),
    array('id'=>'uk-icon-leaf', 'text'=>'leaf'),
    array('id'=>'uk-icon-legal', 'text'=>'legal <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-lemon-o', 'text'=>'lemon-o'),
    array('id'=>'uk-icon-level-down', 'text'=>'level-down'),
    array('id'=>'uk-icon-level-up', 'text'=>'level-up'),
    array('id'=>'uk-icon-life-bouy', 'text'=>'life-bouy <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-life-buoy', 'text'=>'life-buoy <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-life-ring', 'text'=>'life-ring'),
    array('id'=>'uk-icon-life-ring uk-icon-spin', 'text'=>'life-ring <span class="uk-text-muted">(spin)</span>'),
    array('id'=>'uk-icon-life-saver', 'text'=>'life-saver <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-lightbulb-o', 'text'=>'lightbulb-o'),
    array('id'=>'uk-icon-line-chart', 'text'=>'line-chart'),
    array('id'=>'uk-icon-location-arrow', 'text'=>'location-arrow'),
    array('id'=>'uk-icon-location-arrow uk-icon-spin', 'text'=>'location-arrow <span class="uk-text-muted">(spin)</span>'),
    array('id'=>'uk-icon-lock', 'text'=>'lock'),
    array('id'=>'uk-icon-magic', 'text'=>'magic'),
    array('id'=>'uk-icon-magnet', 'text'=>'magnet'),
    array('id'=>'uk-icon-magnet uk-icon-spin', 'text'=>'magnet <span class="uk-text-muted">(spin)</span>'),
    array('id'=>'uk-icon-mail-forward', 'text'=>'mail-forward <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-mail-reply', 'text'=>'mail-reply <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-mail-reply-all', 'text'=>'mail-reply-all <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-male', 'text'=>'male'),
    array('id'=>'uk-icon-map', 'text'=>'map'),
    array('id'=>'uk-icon-map-marker', 'text'=>'map-marker'),
    array('id'=>'uk-icon-map-o', 'text'=>'map-o'),
    array('id'=>'uk-icon-map-pin', 'text'=>'map-pin'),
    array('id'=>'uk-icon-map-signs', 'text'=>'map-signs'),
    array('id'=>'uk-icon-meh-o', 'text'=>'meh-o'),
    array('id'=>'uk-icon-microphone', 'text'=>'microphone'),
    array('id'=>'uk-icon-microphone-slash', 'text'=>'microphone-slash'),
    array('id'=>'uk-icon-minus', 'text'=>'minus'),
    
    array('id'=>'uk-icon-minus-circle', 'text'=>'minus-circle'),
    array('id'=>'uk-icon-minus-square', 'text'=>'minus-square'),
    array('id'=>'uk-icon-minus-square-o', 'text'=>'minus-square-o'),
    array('id'=>'uk-icon-mobile', 'text'=>'mobile'),
    array('id'=>'uk-icon-mobile-phone', 'text'=>'mobile-phone <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-money', 'text'=>'money'),
    array('id'=>'uk-icon-moon-o', 'text'=>'moon-o'),
    array('id'=>'uk-icon-moon-o uk-icon-spin', 'text'=>'moon-o <span class="uk-text-muted">(spin)</span>'),
    array('id'=>'uk-icon-mortar-board', 'text'=>'mortar-board <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-motorcycle', 'text'=>'motorcycle'),
    array('id'=>'uk-icon-mouse-pointer', 'text'=>'mouse-pointer'),
    array('id'=>'uk-icon-music', 'text'=>'music'),
    array('id'=>'uk-icon-navicon', 'text'=>'navicon <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-newspaper-o', 'text'=>'newspaper-o'),
    array('id'=>'uk-icon-object-group', 'text'=>'object-group'),
    array('id'=>'uk-icon-object-ungroup', 'text'=>'object-ungroup'),
    array('id'=>'uk-icon-paint-brush', 'text'=>'paint-brush'),
    array('id'=>'uk-icon-paper-plane', 'text'=>'paper-plane'),
    array('id'=>'uk-icon-paper-plane-o', 'text'=>'paper-plane-o'),
    array('id'=>'uk-icon-paw', 'text'=>'paw'),
    array('id'=>'uk-icon-pencil', 'text'=>'pencil'),
    array('id'=>'uk-icon-pencil-square', 'text'=>'pencil-square'),
    array('id'=>'uk-icon-pencil-square-o', 'text'=>'pencil-square-o'),
    array('id'=>'uk-icon-percent', 'text'=>'percent'),
    array('id'=>'uk-icon-phone', 'text'=>'phone'),
    array('id'=>'uk-icon-phone-square', 'text'=>'phone-square'),
    array('id'=>'uk-icon-photo', 'text'=>'photo <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-picture-o', 'text'=>'picture-o'),
    array('id'=>'uk-icon-pie-chart', 'text'=>'pie-chart'),
    array('id'=>'uk-icon-plane', 'text'=>'plane'),
    array('id'=>'uk-icon-plug', 'text'=>'plug'),
    array('id'=>'uk-icon-plus', 'text'=>'plus'),
    array('id'=>'uk-icon-plus-circle', 'text'=>'plus-circle'),
    array('id'=>'uk-icon-plus-square', 'text'=>'plus-square'),
    array('id'=>'uk-icon-plus-square-o', 'text'=>'plus-square-o'),
    array('id'=>'uk-icon-power-off', 'text'=>'power-off'),
    array('id'=>'uk-icon-print', 'text'=>'print'),
    array('id'=>'uk-icon-puzzle-piece', 'text'=>'puzzle-piece'),
    array('id'=>'uk-icon-qrcode', 'text'=>'qrcode'),
    array('id'=>'uk-icon-question', 'text'=>'question'),
    array('id'=>'uk-icon-question uk-icon-spin', 'text'=>'question <span class="uk-text-muted">(spin)</span>'),
    array('id'=>'uk-icon-question-circle', 'text'=>'question-circle'),
    array('id'=>'uk-icon-quote-left', 'text'=>'quote-left'),
    array('id'=>'uk-icon-quote-right', 'text'=>'quote-right'),
    array('id'=>'uk-icon-random', 'text'=>'random'),
    array('id'=>'uk-icon-recycle', 'text'=>'recycle'),
    array('id'=>'uk-icon-refresh', 'text'=>'refresh'),
    array('id'=>'uk-icon-refresh uk-icon-spin', 'text'=>'refresh <span class="uk-text-muted">(spin)</span>'),
    array('id'=>'uk-icon-registered', 'text'=>'registered'),
    array('id'=>'uk-icon-remove', 'text'=>'remove <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-reorder', 'text'=>'reorder <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-reply', 'text'=>'reply'),
    array('id'=>'uk-icon-reply-all', 'text'=>'reply-all'),
    array('id'=>'uk-icon-retweet', 'text'=>'retweet'),
    array('id'=>'uk-icon-road', 'text'=>'road'),
    array('id'=>'uk-icon-rocket', 'text'=>'rocket'),
    array('id'=>'uk-icon-rss', 'text'=>'rss'),
    array('id'=>'uk-icon-rss-square', 'text'=>'rss-square'),
    array('id'=>'uk-icon-search', 'text'=>'search'),
    array('id'=>'uk-icon-search-minus', 'text'=>'search-minus'),
    array('id'=>'uk-icon-search-plus', 'text'=>'search-plus'),
    array('id'=>'uk-icon-send', 'text'=>'send <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-send-o', 'text'=>'send-o <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-server', 'text'=>'server'),
    array('id'=>'uk-icon-share', 'text'=>'share'),
    array('id'=>'uk-icon-share-alt', 'text'=>'share-alt'),
    array('id'=>'uk-icon-share-alt-square', 'text'=>'share-alt-square'),
    array('id'=>'uk-icon-share-square', 'text'=>'share-square'),
    array('id'=>'uk-icon-share-square-o', 'text'=>'share-square-o'),
    array('id'=>'uk-icon-shield', 'text'=>'shield'),
    array('id'=>'uk-icon-ship', 'text'=>'ship'),
    array('id'=>'uk-icon-shopping-bag', 'text'=>'shopping-bag'),
    array('id'=>'uk-icon-shopping-basket', 'text'=>'shopping-basket'),
    array('id'=>'uk-icon-shopping-cart', 'text'=>'shopping-cart'),
    array('id'=>'uk-icon-sign-in', 'text'=>'sign-in'),
    array('id'=>'uk-icon-sign-out', 'text'=>'sign-out'),
    array('id'=>'uk-icon-signal', 'text'=>'signal'),
    array('id'=>'uk-icon-sitemap', 'text'=>'sitemap'),
    array('id'=>'uk-icon-sliders', 'text'=>'sliders'),
    array('id'=>'uk-icon-smile-o', 'text'=>'smile-o'),
    array('id'=>'uk-icon-smile-o uk-icon-spin', 'text'=>'smile-o <span class="uk-text-muted">(spin)</span>'),
    array('id'=>'uk-icon-soccer-ball-o', 'text'=>'soccer-ball-o <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-sort', 'text'=>'sort'),
    array('id'=>'uk-icon-sort uk-icon-spin', 'text'=>'sort <span class="uk-text-muted">(spin)</span>'),
    array('id'=>'uk-icon-sort-alpha-asc', 'text'=>'sort-alpha-asc'),
    array('id'=>'uk-icon-sort-alpha-desc', 'text'=>'sort-alpha-desc'),
    array('id'=>'uk-icon-sort-amount-asc', 'text'=>'sort-amount-asc'),
    array('id'=>'uk-icon-sort-amount-desc', 'text'=>'sort-amount-desc'),
    array('id'=>'uk-icon-sort-asc', 'text'=>'sort-asc'),
    array('id'=>'uk-icon-sort-asc uk-icon-spin', 'text'=>'sort-asc <span class="uk-text-muted">(spin)</span>'),
    array('id'=>'uk-icon-sort-desc', 'text'=>'sort-desc'),
    array('id'=>'uk-icon-sort-down', 'text'=>'sort-down <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-sort-numeric-asc', 'text'=>'sort-numeric-asc'),
    array('id'=>'uk-icon-sort-numeric-desc', 'text'=>'sort-numeric-desc'),
    array('id'=>'uk-icon-sort-up', 'text'=>'sort-up <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-space-shuttle', 'text'=>'space-shuttle'),
    array('id'=>'uk-icon-spinner', 'text'=>'spinner'),
    array('id'=>'uk-icon-spinner uk-icon-spin', 'text'=>'spinner <span class="uk-text-muted">(spin)</span>'),
    array('id'=>'uk-icon-spoon', 'text'=>'spoon'),
    array('id'=>'uk-icon-square', 'text'=>'square'),
    array('id'=>'uk-icon-square-o', 'text'=>'square-o'),
    array('id'=>'uk-icon-star', 'text'=>'star'),
    array('id'=>'uk-icon-star uk-icon-spin', 'text'=>'star <span class="uk-text-muted">(spin)</span>'),
    array('id'=>'uk-icon-star-half', 'text'=>'star-half'),
    array('id'=>'uk-icon-star-half-empty', 'text'=>'star-half-empty <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-star-half-full', 'text'=>'star-half-full <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-star-half-o', 'text'=>'star-half-o'),
    array('id'=>'uk-icon-star-o', 'text'=>'star-o'),
    array('id'=>'uk-icon-star-o uk-icon-spin', 'text'=>'star-o <span class="uk-text-muted">(spin)</span>'),
    array('id'=>'uk-icon-sticky-note', 'text'=>'sticky-note'),
    array('id'=>'uk-icon-sticky-note-o', 'text'=>'sticky-note-o'),
    array('id'=>'uk-icon-street-view', 'text'=>'street-view'),
    array('id'=>'uk-icon-suitcase', 'text'=>'suitcase'),
    array('id'=>'uk-icon-sun-o', 'text'=>'sun-o'),
    array('id'=>'uk-icon-support', 'text'=>'support <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-tablet', 'text'=>'tablet'),
    array('id'=>'uk-icon-tachometer', 'text'=>'tachometer'),
    array('id'=>'uk-icon-tag', 'text'=>'tag'),
    array('id'=>'uk-icon-tags', 'text'=>'tags'),
    array('id'=>'uk-icon-tasks', 'text'=>'tasks'),
    array('id'=>'uk-icon-taxi', 'text'=>'taxi'),
    array('id'=>'uk-icon-television', 'text'=>'television'),
    array('id'=>'uk-icon-terminal', 'text'=>'terminal'),
    array('id'=>'uk-icon-thumb-tack', 'text'=>'thumb-tack'),
    array('id'=>'uk-icon-thumbs-down', 'text'=>'thumbs-down'),
    array('id'=>'uk-icon-thumbs-o-down', 'text'=>'thumbs-o-down'),
    array('id'=>'uk-icon-thumbs-o-up', 'text'=>'thumbs-o-up'),
    array('id'=>'uk-icon-thumbs-up', 'text'=>'thumbs-up'),
    array('id'=>'uk-icon-ticket', 'text'=>'ticket'),
    array('id'=>'uk-icon-times', 'text'=>'times'),
    array('id'=>'uk-icon-times uk-icon-spin', 'text'=>'times <span class="uk-text-muted">(spin)</span>'),
    array('id'=>'uk-icon-times-circle', 'text'=>'times-circle'),
    array('id'=>'uk-icon-times-circle-o', 'text'=>'times-circle-o'),
    array('id'=>'uk-icon-tint', 'text'=>'tint'),
    array('id'=>'uk-icon-toggle-down', 'text'=>'toggle-down <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-toggle-left', 'text'=>'toggle-left <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-toggle-off', 'text'=>'toggle-off'),
    array('id'=>'uk-icon-toggle-on', 'text'=>'toggle-on'),
    array('id'=>'uk-icon-toggle-right', 'text'=>'toggle-right <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-toggle-up', 'text'=>'toggle-up <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-trademark', 'text'=>'trademark'),
    array('id'=>'uk-icon-trash', 'text'=>'trash'),
    array('id'=>'uk-icon-trash-o', 'text'=>'trash-o'),
    array('id'=>'uk-icon-tree', 'text'=>'tree'),
    array('id'=>'uk-icon-trophy', 'text'=>'trophy'),
    array('id'=>'uk-icon-truck', 'text'=>'truck'),
    array('id'=>'uk-icon-tty', 'text'=>'tty'),
    array('id'=>'uk-icon-tv', 'text'=>'tv <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-umbrella', 'text'=>'umbrella'),
    array('id'=>'uk-icon-university', 'text'=>'university'),
    array('id'=>'uk-icon-unlock', 'text'=>'unlock'),
    array('id'=>'uk-icon-unlock-alt', 'text'=>'unlock-alt'),
    array('id'=>'uk-icon-unsorted', 'text'=>'unsorted <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-upload', 'text'=>'upload'),
    array('id'=>'uk-icon-usb', 'text'=>'usb'),
    array('id'=>'uk-icon-user', 'text'=>'user'),
    array('id'=>'uk-icon-user-plus', 'text'=>'user-plus'),
    array('id'=>'uk-icon-user-secret', 'text'=>'user-secret'),
    array('id'=>'uk-icon-user-times', 'text'=>'user-times'),
    array('id'=>'uk-icon-users', 'text'=>'users'),
    array('id'=>'uk-icon-video-camera', 'text'=>'video-camera'),
    array('id'=>'uk-icon-volume-down', 'text'=>'volume-down'),
    array('id'=>'uk-icon-volume-off', 'text'=>'volume-off'),
    array('id'=>'uk-icon-volume-up', 'text'=>'volume-up'),
    array('id'=>'uk-icon-warning', 'text'=>'warning <span class="uk-text-muted">(alias)</span>'),
    array('id'=>'uk-icon-wheelchair', 'text'=>'wheelchair'),
    array('id'=>'uk-icon-wifi', 'text'=>'wifi'),
    array('id'=>'uk-icon-wrench', 'text'=>'wrench'),
);

return json_encode($ret);